# Generated by Django 6.0.7 on 2026-07-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('billiards', 'بلياردو'), ('snooker', 'سنوكر'), ('cards', 'ورق')], max_length=20)),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('hourly_price', models.DecimalField(decimal_places=2, default=5.0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'طاولة',
                'verbose_name_plural': 'الطاولات',
                'ordering': ['game_type', 'number'],
                'unique_together': {('game_type', 'number')},
            },
        ),
    ]
