# Generated by Django 6.0.7 on 2026-07-19 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='عالم السنوكر', max_length=100)),
                ('location', models.CharField(default='إربد - دوار السلطان', max_length=200)),
                ('whatsapp', models.CharField(default='962790000000', max_length=20)),
                ('opening_hours', models.CharField(default='10:00 ص — 2:00 ص', max_length=100)),
                ('about', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'إعدادات النادي',
                'verbose_name_plural': 'إعدادات النادي',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('post_type', models.CharField(choices=[('news', 'خبر'), ('tournament', 'إعلان بطولة'), ('winner', 'فائز'), ('photo', 'صورة'), ('offer', 'عرض')], default='news', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/')),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'منشور',
                'verbose_name_plural': 'المنشورات',
                'ordering': ['-published_at', '-id'],
            },
        ),
    ]
