# Generated by Django 6.0.7 on 2026-07-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('billiards', 'بلياردو'), ('snooker', 'سنوكر'), ('cards', 'ورق')], max_length=20)),
                ('player1_name', models.CharField(blank=True, max_length=120)),
                ('player2_name', models.CharField(blank=True, max_length=120)),
                ('score1', models.PositiveIntegerField(default=0)),
                ('score2', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'مجدول'), ('live', 'مباشر'), ('paused', 'متوقف'), ('completed', 'منتهي'), ('cancelled', 'ملغي')], default='scheduled', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('round_label', models.CharField(blank=True, max_length=80)),
                ('winner_name', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مباراة',
                'verbose_name_plural': 'المباريات',
                'ordering': ['-scheduled_at', '-created_at'],
            },
        ),
    ]
