# Generated by Django 6.0.7 on 2026-07-19 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True)),
                ('game_type', models.CharField(choices=[('billiards', 'بلياردو'), ('snooker', 'سنوكر'), ('cards', 'ورق')], max_length=20)),
                ('format', models.CharField(choices=[('knockout', 'إقصائي'), ('groups', 'مجموعات'), ('league', 'دوري')], default='knockout', max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'قادم'), ('current', 'جاري'), ('previous', 'سابق'), ('cancelled', 'ملغي')], default='upcoming', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('prize_info', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('max_participants', models.PositiveIntegerField(default=16)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='tournaments/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'بطولة',
                'verbose_name_plural': 'البطولات',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('ranking', models.PositiveIntegerField(default=0)),
                ('seed', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('is_eliminated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'لاعب',
                'verbose_name_plural': 'اللاعبون',
                'ordering': ['seed', 'ranking', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BracketNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField()),
                ('match', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracket_node', to='matches.match')),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracket_as_p1', to='tournaments.player')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracket_as_p2', to='tournaments.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracket_wins', to='tournaments.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bracket_nodes', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['round_number', 'position'],
                'unique_together': {('tournament', 'round_number', 'position')},
            },
        ),
    ]
